### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by up-ls** [QingZhuanya/corridor_Bspline_optimization#1]
![image](https://github.com/user-attachments/assets/9f782dae-267b-4d6a-ac7b-313819856f0e)

Hello, I encountered this problem when running the code. How should I solve it? please

**Comment by QingZhuanya** [comment]
You should install glog library&nbsp;



发自我的iPhone


------------------ Original ------------------
From: upls_ky ***@***.***&gt;
Date: Wed,Aug 7,2024 11:06 AM
To: QingZhuanya/corridor_Bspline_optimization ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [QingZhuanya/corridor_Bspline_optimization] Runtime Error (Issue #1)





 
image.png (view on web)
 
Hello, I encountered this problem when running the code. How should I solve it? please

**Comment by up-ls** [comment]
> You should install glog library&nbsp; 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: upls_ky ***@***.***&gt; Date: Wed,Aug 7,2024 11:06 AM To: QingZhuanya/corridor_Bspline_optimization ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [QingZhuanya/corridor_Bspline_optimization] Runtime Error (Issue #1) image.png (view on web) Hello, I encountered this problem when running the code. How should I solve it? please — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![image](https://github.com/user-attachments/assets/f5059fa9-8805-401a-a83f-330cbb0dd34f)
Thank you, this problem is solved. There is a new problem, and I haven't found a solution yet.

**Comment by QingZhuanya** [comment]
Sorry! and I have never encountered this problem before. you could try clone it again?

**Comment by up-ls** [comment]
Hello, I encountered a new problem when running the code. How should I solve it? Looking forward to your answer.
![1](https://github.com/user-attachments/assets/ff048a55-c79e-476a-bd92-2a57c0095139)

**Comment by QingZhuanya** [comment]
> Hello, I encountered a new problem when running the code. How should I solve it? Looking forward to your answer. ![1](https://private-user-images.githubusercontent.com/55660435/358916745-ff048a55-c79e-476a-bd92-2a57c0095139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mzg3NDYsIm5iZiI6MTcyNDYzODQ0NiwicGF0aCI6Ii81NTY2MDQzNS8zNTg5MTY3NDUtZmYwNDhhNTUtYzc5ZS00NzZhLWJkOTItMmE1N2MwMDk1MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyMTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MWE1MTRjMjdjYzBmNWE2NGIzMjQzZjYwNjhkYWEyYTg2Mjk2ZGE1NmUwYzBhOTRhNjFjM2Y5MjYwOGZjMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ko-ZsaBCI7dgvJHNttietcfWCAPVlGUEGLYRsOsOq9c)

install matplotcpp https://blog.csdn.net/weixin_37835423/article/details/126159205
